maven-test:
  stage: test
  script:
    - mvn clean package

maven-build:
  stage: build
  script:
    - mvn clean install

maven-deploy:
  stage: deploy
  script:
    - export MAVEN_OPTS='-Xmx128m'
    - mvn clean install
  artifacts:
    paths:
    - target/*.jar
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
